name: RRenderer CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, dev]

jobs:
  lint:
    name: Linting phase
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4

      - name: Install LLVM 19
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 19
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-19 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-19 100
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-19 100

      - name: clang-tidy
        run: clang-tidy --quiet -p build --warnings-as-errors=* $(find src/ -name '*.cpp' -or -name '*.hpp')

  build-and-test:
    name: Build phase
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ ninja-build vulkan-tools libvulkan-dev glslang-tools glslang-dev xorg-dev libx11-dev mesa-common-dev libwayland-dev wayland-protocols libxkbcommon-dev

      - name: Configure CMake
        run: cmake --preset release

      - name: Build
        run: cmake --build --preset release

      - name: Test
        run: ctest --test-dir build/release/test/ --rerun-failed --output-on-failure
