name: Formatting
on:
  push:
    branches:
      - dev

jobs:
  clang-format:
    name: Format with clang-format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt install -y clang-format-19 && alias clang-format="clang-format-19"

      - name: Set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run clang-format
        run: |
          find ./src \
            -regex '.*\.\(cpp\|hpp\)' \
            -exec clang-format -i {} +

      - name: Commit and Push
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "Everything is already formatted"
          else
            git commit -m "chore: fix formatting with clang-format [skip ci]"
            git push
          fi
